### ISSUE TITLE
エラーで動かない...

### ISSUE THREAD

**Issue by rild** [rild/fft_demo#1]
`recode.py` の41行目でエラーが出ているみたい

```sh
$ python record.py 2 test.wav
start recoding
Traceback (most recent call last):
  File "record.py", line 62, in <module>
    record(float(record_seconds), output_filename)
  File "record.py", line 41, in record
    data = stream.read(min(BUF_SIZE * remain_samples))
TypeError: 'int' object is not iterable
```

**Comment by rild** [comment]
```py
    print "times"
    print len(times)
    print times
    print "waveform"
    print len(waveform)
    print waveform
```

これでデバッグ


```sh
times
160370
[0 0 0 ..., 3 3 3]
waveform
160370
[[-0.00442505 -0.00323486]
 [-0.00479126 -0.00354004]
 [-0.0045166  -0.00341797]
 ...,
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]
```

**Comment by rild** [comment]
<img width=320 src="https://gyazo.com/506007c96d13cb0a28c155e88b9db584.png">

整数のところに偏ってるうううう

**Comment by rild** [comment]
<img width=320 src="https://gyazo.com/0a1e505f4c45102e98ae9e20c71dbe61.png">

っぽい感じになった

**Comment by rild** [comment]
# 変更箇所
## Before

```py
times = numpy.arange(len(waveform)) / sampling_rate # 各サンプルの時刻
```

## After

```py
times = numpy.arange(float(len(waveform))) / sampling_rate # 各サンプルの時刻
```

**Comment by rild** [comment]
```sh
times (int..?)
[0 0 0 ..., 3 3 3]
times (float..?)
[  0.00000000e+00   2.26757370e-05   4.53514739e-05 ...,   3.63643991e+00
   3.63646259e+00   3.63648526e+00]
```

**Comment by rild** [comment]
# 蛇足
wavファイル読み込み時にモノラルにしないとダメかなぁと思った

```py
def load_wav(filename):
    try:
        wavedata=scipy.io.wavfile.read(filename)
        samplerate=int(wavedata[0])
        smp=wavedata[1]*(1.0/32768.0) # pcm
        if len(smp.shape)>1: #convert to mono
            smp=(smp[:,0]+smp[:,1])*0.5
        return (samplerate,smp)
    except:
        print ("Error loading wav: "+filename)
        return None
```

**やらなくても良さげ**

**Comment by rild** [comment]
github markdown コードブロックシンタックスハイライト
- https://github.com/su324749/markdown-memo/blob/master/markdown.md

**Comment by rild** [comment]
解決したのでクローズ
