### ISSUE TITLE
recode.py が実行できない

### ISSUE THREAD

**Issue by rild** [rild/fft_demo#2]
# What 
ファイルがエラーで実行ができない

# 起きていること

```sh
$ python record.py 2 test.wav
start recoding
Traceback (most recent call last):
  File "record.py", line 62, in <module>
    record(float(record_seconds), output_filename)
  File "record.py", line 41, in record
    data = stream.read(min(BUF_SIZE * remain_samples))
TypeError: 'int' object is not iterable
```

**Comment by rild** [comment]
https://docs.python.jp/2.7/library/io.html

>read(n=-1)(原文)
オブジェクトを n バイトまで読み込み、それを返します。簡単のため、 n が指定されていないか -1 なら、 readall() が呼び出されます。そうでなければ、システムコール呼び出しが一度だけ行われます。既に EOF に達していたら空のバイトオブジェクトが返されます。オペレーティングシステムコールが返したものがが n バイトより少なければ、 n バイトより少なく返されることがあります。
0 バイトが返って、 n が 0 でなければ、それはファイルの終端を表します。オブジェクトがノンブロッキングモードで、 1 バイトも読み込めなければ、 None が返されます。

**Comment by rild** [comment]
エラーは `min` 関数に int 型の変数を渡していることが原因かと

**Comment by rild** [comment]
- [PyAudio Documentation¶](https://people.csail.mit.edu/hubert/pyaudio/docs/)

**Comment by rild** [comment]
```py
# data = stream.read(min(BUF_SIZE * remain_samples))
data = stream.read(min(BUF_SIZE, remain_samples))
```

なぜか `*` にしていたっていう。

**Comment by rild** [comment]
解決。クローズ
